export function Expenses() {
  return (
    <div className="flex flex-col pt-20 pb-15 w-full ">
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
      <span>Testanto</span>
    </div>
  )
}